# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

vars:
  DEFAULT_CONFIG: Release
  DEFAULT_PLATFORM: x64
  DEFAULT_SOLUTION: wcap.sln

tasks:
  default:
    cmds:
      - task: build

  fxc:
    label: "{{ .FXC_SHADER_NAME }}"
    requires:
      vars: [FXC_SHADER_NAME]
    vars:
      FXC_EXE:
        sh: | # shell
          strings=("10.0.26100.0" "10.22621.0")
          for str in "${strings[@]}"
          do
            result="C:/Program Files (x86)/Windows Kits/10/bin/${str}/x64/fxc.exe"
            if [ -e "$result" ]; then
              echo "$result"
              break
            fi
          done
    env:
      FXC_DEBUG: /Od /Zi
      FXC_RELEASE: /O3 /Qstrip_reflect /Qstrip_debug /Qstrip_priv
      FXC: '{{ if eq .CONFIG "Release" }}{{ .FXC_RELEASE }}{{ else }}{{ .FXC_DEBUG }}{{ end }}'
    sources:
      - wcap_shaders.hlsl
    generates:
      - shaders/{{ .FXC_SHADER_NAME }}.dxbc
      - shaders/{{ .FXC_SHADER_NAME }}.dcs
      - shaders/{{ .FXC_SHADER_NAME }}.h
    cmds:
      - cmd: | # shell
          mkdir -p shaders
      - cmd: | # shell
          # ...
          "{{.FXC_EXE}}" /nologo \
            $FXC /WX /Ges /T cs_5_0  \
            /E "{{ .FXC_SHADER_NAME }}" \
            /Fo "shaders/{{ .FXC_SHADER_NAME }}.dxbc" \
            /Fc "shaders/{{ .FXC_SHADER_NAME }}.asm" \
            wcap_shaders.hlsl
      - cmd: | # shell
          # ...
          "{{.FXC_EXE}}" /nologo \
            /compress \
            /Vn "{{ .FXC_SHADER_NAME }}ShaderBytes" \
            /Fo "shaders/{{ .FXC_SHADER_NAME }}.dcs" \
            /Fh "shaders/{{ .FXC_SHADER_NAME }}.h" \
            "shaders/{{ .FXC_SHADER_NAME }}.dxbc"

  shaders:
    deps:
      - for:
          matrix:
            OS: [
              "ResizePassH",
              "ResizePassV",
              "ResizeLinearPassH",
              "ResizeLinearPassV",
              "ConvertSinglePass",
              "ConvertPass1",
              "ConvertPass2"
            ]
        task: fxc
        vars: { FXC_SHADER_NAME: "{{.ITEM.OS}}" }

  build:
    deps: [shaders]
    aliases: [b, bld]
    silent: true
    vars:
      MSVC_ROOT:
        sh: |
          "C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" \
            -latest -requires Microsoft.VisualStudio.Workload.NativeDesktop -property installationPath
      GIT_TAG:
        sh: git describe --always --dirty
    env:
      __VSCMD_ARG_NO_LOGO: 1

      CL_DEBUG: /MTd /Od /Zi /D_DEBUG /RTC1 /Fdwcap.pdb /fsanitize=address
      LINK_DEBUG: /DEBUG

      CL_RELEASE: /GL /O1 /Oi /DNDEBUG /GS-
      LINK_RELEASE: /LTCG /OPT:REF /OPT:ICF ucrt.lib libvcruntime.lib

      CL: '{{ if eq .CONFIG "Release" }}{{ .CL_RELEASE }}{{ else }}{{ .CL_DEBUG }}{{ end }}'
      LINK: '{{ if eq .CONFIG "Release" }}{{ .LINK_RELEASE }}{{ else }}{{ .LINK_DEBUG }}{{ end }}'
      VSVARS: '{{ joinPath .MSVC_ROOT "VC/Auxiliary/Build/vcvarsall.bat" | fromSlash }}'
    sources:
      - wcap.sln
      - wcap.manifest
      - wcap.vcxproj*
      - wcap*.c
      - wcap*.h
      - wcap*.ico
      - wcap*.rc
      - shaders/
    generates:
      - bin/x64/{{.MSBUILD_CONFIG}}/wcap.*
    cmds:
      - cmd: >-
          cmd.exe /d /e:on /c "
          "$VSVARS" x64
          && rc.exe /nologo wcap.rc
          && cl.exe /nologo
          /W3 /WX
          -DWCAP_GIT_INFO="{{.GIT_TAG}}"
          wcap.c wcap.res
          /link /INCREMENTAL:NO
          /MANIFEST:EMBED /MANIFESTINPUT:wcap.manifest
          /SUBSYSTEM:WINDOWS /FIXED /merge:_RDATA=.rdata
          "

  msbuild:
    deps: [shaders]
    silent: true
    vars:
      MSBUILD:
        sh: | # shell
          strings=("Preview" "Enterprise" "Professional" "Community")
          for str in "${strings[@]}"
          do
            result="C:/Program Files/Microsoft Visual Studio/2022/${str}/MSBuild/Current/Bin/MSBuild.exe"
            if [ -e "$result" ]; then
              echo "$result"
              break
            fi
          done
      MSBUILD_CONFIG: '{{ .CONFIG | default .DEFAULT_CONFIG }}'
      MSBUILD_SOLUTION: '{{ joinPath .TASKFILE_DIR (.SOLUTION | default .DEFAULT_SOLUTION) }}'
      MSBUILD_PLATFORM: '{{ .PLATFORM | default .DEFAULT_PLATFORM }}'
    sources:
      - wcap.sln
      - wcap.manifest
      - wcap.vcxproj*
      - wcap*.c
      - wcap*.h
      - wcap*.ico
      - wcap*.rc
      - shaders/
    generates:
      - bin/x64/{{.MSBUILD_CONFIG}}/wcap.*
    cmds:
      - cmd: >-
          "{{fromSlash .MSBUILD}}"
          /m
          /t:Build
          /p:Configuration="{{.MSBUILD_CONFIG}}"
          /p:Platform="{{.MSBUILD_PLATFORM}}"
          "{{fromSlash .MSBUILD_SOLUTION}}"
